name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_CLIENT_ID }}
        password: ${{ secrets.ACR_CLIENT_SECRET }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ secrets.ACR_REPOSITORY }}:${{ secrets.ACR_IMAGE_TAG }}
        file: ./Dockerfile

    - name: Set up kubeconfig
      uses: azure/k8s-set-context@v3
      with:
        resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy to AKS
      uses: azure/k8s-deploy@v4
      with:
        namespace: ${{ secrets.ACR_REPOSITORY }}
        manifests: ./manifests/deployment.yaml, ./manifests/service.yaml